FROM maven:3.9.6-eclipse-temurin-17
WORKDIR /app
RUN mvn dependency:go-offline
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=0 /app/target/scouting-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
