name: Java CI with Docker Build and SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_analyze:
    name: Build Docker Image, Run Tests & SonarQube Analysis
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: scoutingdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: tmpPass
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug - Lister les fichiers pour valider le chemin
        run: ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker image
        working-directory: Exercice-DDD/scouting-service
        run: docker build -t scouting-service .

      - name: Run Maven tests in Docker
        working-directory: Exercice-DDD/scouting-service
        run: |
          docker run --rm \
            --network host \
            -e POSTGRES_DB=scoutingdb \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=tmpPass \
            -v "$(pwd)":/usr/src/app \
            -w /usr/src/app \
            maven:3.8.8-eclipse-temurin-21 \
            mvn clean verify

      - name: Run SonarQube Analysis
        working-directory: Exercice-DDD/scouting-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run --rm \
            --network host \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v "$(pwd)":/usr/src/app \
            -w /usr/src/app \
            maven:3.8.8-eclipse-temurin-21 \
            mvn sonar:sonar \
              -Dsonar.projectKey=scouting-service \
              -Dsonar.host.url=https://c1b0-197-230-25-154.ngrok-free.app \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Shutdown Docker Compose services (if any)
        working-directory: Exercice-DDD/scouting-service
        run: docker-compose down || true

