name: Java CI/CD with Docker and SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_scan_deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: scoutingdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: tmpPass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show working directory
        run: ls -la

      - name: Build project with Maven (tests included)
        working-directory: scouting-service
        run: |
          docker run --rm \
            --network host \
            -e POSTGRES_DB=scoutingdb \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=tmpPass \
            -v "$PWD":/app \
            -w /app \
            maven:3.8.8-eclipse-temurin-21 \
            mvn clean verify

      - name: SonarQube Analysis
        working-directory: scouting-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run --rm \
            --network host \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v "$PWD":/app \
            -w /app \
            maven:3.8.8-eclipse-temurin-21 \
            mvn sonar:sonar \
              -Dsonar.projectKey=scouting-service \
              -Dsonar.host.url=https://bc4f-105-66-132-136.ngrok-free.app \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Trivy scan - codebase
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Build Docker image
        run: |
          docker build -t scouting-app:latest -f scouting-service/dockerfile scouting-service

      - name: Trivy scan - Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'scouting-app:latest'
          format: 'table'
          ignore-unfixed: true
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag and push image to Docker Hub
        env:
          IMAGE_NAME: scouting-app
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          DATE_TAG=$(date +'%Y-%m-%d-%H%M')
          docker tag $IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:$DATE_TAG
          docker tag $IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$DATE_TAG
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
