name: Java CI with Docker and SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: scoutingdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: tmpPass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show working directory
        run: ls -la

      - name: Build project with Maven (tests included)
        working-directory: scouting-service
        run: |
          docker run --rm \
            --network host \
            -e POSTGRES_DB=scoutingdb \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=tmpPass \
            -v "$PWD":/app \
            -w /app \
            maven:3.8.8-eclipse-temurin-21 \
            mvn clean verify

      # ✅ Scan codebase avec Trivy
      - name: Trivy scan - codebase
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          ignore-unfixed: true
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      # 🐳 Build Docker image
      - name: Build Docker image
        run: docker build -t scouting-app:latest -f scouting-service/dockerfile scouting-service

      # 🔍 Trivy scan - image Docker
      - name: Trivy scan - Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'scouting-app:latest'
          format: 'table'
          ignore-unfixed: true
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
